name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Hoặc main nếu bạn dùng main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build project
        run: |
          # Thay lệnh build này nếu bạn dùng framework khác
          npm install
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build  # Thay đổi nếu thư mục build của bạn khác
